### ISSUE TITLE
screen returns non-zero exit status 1

### ISSUE THREAD

**Issue by arialdomartini** [hydrargyrum/asciinario#1]
Executing 

```bash
./asciinario.py demo.asciinario my.cast 2> errors.txt
```

I get in `errors.txt` the following:

```
Traceback (most recent call last):
  File "/home/arialdo/tmp/asciinario/./asciinario.py", line 129, in <module>
    play_inscript(instructions, screen_id)
  File "/home/arialdo/tmp/asciinario/./asciinario.py", line 111, in play_inscript
    player.do(line)
  File "/home/arialdo/tmp/asciinario/./asciinario.py", line 23, in do
    return method(self, match)
  File "/home/arialdo/tmp/asciinario/./asciinario.py", line 32, in do_status_change
    self.send_screen("hardstatus", "alwaysfirstline")
  File "/home/arialdo/tmp/asciinario/./asciinario.py", line 89, in send_screen
    subprocess.check_output(["screen", "-S", self.screen_id, "-X", *args])
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['screen', '-S', '792e45e6-6928-4f0d-84ea-a673a29094cd', '-X', 'hardstatus', 'alwaysfirstline']' returned non-zero exit status 1.
asciinema: recording asciicast to my.cast
asciinema: exit opened program when you're done
```

Here's my setup:

```bash
❯ python --version
Python 3.10.9
❯ screen --version
Screen version 4.09.00 (GNU) 30-Jan-22
❯ asciinema --version
asciinema 2.2.0
```

Any idea? Thank you very much!

**Comment by hydrargyrum** [comment]
I think the issue was that not enough time was given to screen to start properly. I now poll screen for a few seconds, that should hopefully be enough. Can you git-pull and test again?

**Comment by arialdomartini** [comment]
Sure! In 9f7574a25ff6318be9004a489c0e8bf9ae6c3f08 it works perfectly! Thank you!
